version: '3'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile  # Chemin vers le Dockerfile personnalisé
    volumes:
      - .:/var/www/html
    ports:
      - "8080:80"
    depends_on:
      - database
    networks:
      - mynetwork


  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: 0000
      MYSQL_DATABASE: internship
      MYSQL_USER: root
    ports:
      - "3307:3306"
    networks:
      - mynetwork


volumes:
  database_data:

networks:
  mynetwork:
